package CardGameLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int And = 1;
  public static final int Card = 2;
  public static final int Command = 3;
  public static final int Deck = 4;
  public static final int Empty = 5;
  public static final int Game = 6;
  public static final int IntValue = 7;
  public static final int Kamu = 8;
  public static final int LogicalExpression = 9;
  public static final int Move = 10;
  public static final int MoveAll = 11;
  public static final int MoveSelected = 12;
  public static final int Not = 13;
  public static final int Operator = 14;
  public static final int Optional = 15;
  public static final int Or = 16;
  public static final int Phase = 17;
  public static final int Pile = 18;
  public static final int Player = 19;
  public static final int Property = 20;
  public static final int Select = 21;
  public static final int SelectCard = 22;
  public static final int SelectPile = 23;
  public static final int Shuffle = 24;
  public static final int StringValue = 25;
  public static final int Token = 26;
  public static final int Turn = 27;
  public static final int Value = 28;
  public static final int While = 29;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xe94dfae4e9d04770L, 0x965c58db5e543504L);
    builder.put(0x26431eee60b75212L, Action);
    builder.put(0x26431eee60b81fc2L, And);
    builder.put(0x568258613b824594L, Card);
    builder.put(0x26431eee60b7ca73L, Command);
    builder.put(0x568258613b8467c7L, Deck);
    builder.put(0x26431eee60b7ca49L, Empty);
    builder.put(0x39b65bcfb2f86776L, Game);
    builder.put(0x568258613b82ce75L, IntValue);
    builder.put(0x26431eee60b85597L, Kamu);
    builder.put(0x26431eee60b7ca3eL, LogicalExpression);
    builder.put(0x26431eee60b75215L, Move);
    builder.put(0x26431eee60b79ac9L, MoveAll);
    builder.put(0x26431eee60b7b86cL, MoveSelected);
    builder.put(0x26431eee60b7ca3dL, Not);
    builder.put(0x26431eee60b81fbcL, Operator);
    builder.put(0x26431eee60b85598L, Optional);
    builder.put(0x26431eee60b81fc3L, Or);
    builder.put(0x26431eee60b1bc56L, Phase);
    builder.put(0x39b65bcfb2f83152L, Pile);
    builder.put(0x39b65bcfb2f7900fL, Player);
    builder.put(0x568258613b82e0a7L, Property);
    builder.put(0x26431eee60b88f78L, Select);
    builder.put(0x26431eee60b88f7cL, SelectCard);
    builder.put(0x26431eee60b88f79L, SelectPile);
    builder.put(0x26431eee60b76900L, Shuffle);
    builder.put(0x568258613b82ce76L, StringValue);
    builder.put(0x568258613b824595L, Token);
    builder.put(0x26431eee60b82ce6L, Turn);
    builder.put(0x568258613b82ce7bL, Value);
    builder.put(0x26431eee60b7ca4aL, While);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
