package CardGameLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptAnd = createDescriptorForAnd();
  /*package*/ final ConceptDescriptor myConceptArgument = createDescriptorForArgument();
  /*package*/ final ConceptDescriptor myConceptCard = createDescriptorForCard();
  /*package*/ final ConceptDescriptor myConceptCardReference = createDescriptorForCardReference();
  /*package*/ final ConceptDescriptor myConceptCollection = createDescriptorForCollection();
  /*package*/ final ConceptDescriptor myConceptCommand = createDescriptorForCommand();
  /*package*/ final ConceptDescriptor myConceptComparator = createDescriptorForComparator();
  /*package*/ final ConceptDescriptor myConceptDeck = createDescriptorForDeck();
  /*package*/ final ConceptDescriptor myConceptEmpty = createDescriptorForEmpty();
  /*package*/ final ConceptDescriptor myConceptEquals = createDescriptorForEquals();
  /*package*/ final ConceptDescriptor myConceptGame = createDescriptorForGame();
  /*package*/ final ConceptDescriptor myConceptIfExpression = createDescriptorForIfExpression();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptIntValue = createDescriptorForIntValue();
  /*package*/ final ConceptDescriptor myConceptKamu = createDescriptorForKamu();
  /*package*/ final ConceptDescriptor myConceptLogicalExpression = createDescriptorForLogicalExpression();
  /*package*/ final ConceptDescriptor myConceptMove = createDescriptorForMove();
  /*package*/ final ConceptDescriptor myConceptMoveAll = createDescriptorForMoveAll();
  /*package*/ final ConceptDescriptor myConceptMoveSelected = createDescriptorForMoveSelected();
  /*package*/ final ConceptDescriptor myConceptNot = createDescriptorForNot();
  /*package*/ final ConceptDescriptor myConceptOperator = createDescriptorForOperator();
  /*package*/ final ConceptDescriptor myConceptOptional = createDescriptorForOptional();
  /*package*/ final ConceptDescriptor myConceptOr = createDescriptorForOr();
  /*package*/ final ConceptDescriptor myConceptPhase = createDescriptorForPhase();
  /*package*/ final ConceptDescriptor myConceptPile = createDescriptorForPile();
  /*package*/ final ConceptDescriptor myConceptPileMethod = createDescriptorForPileMethod();
  /*package*/ final ConceptDescriptor myConceptPileReference = createDescriptorForPileReference();
  /*package*/ final ConceptDescriptor myConceptPlayer = createDescriptorForPlayer();
  /*package*/ final ConceptDescriptor myConceptProperty = createDescriptorForProperty();
  /*package*/ final ConceptDescriptor myConceptPropertyReference = createDescriptorForPropertyReference();
  /*package*/ final ConceptDescriptor myConceptPropertyReferenceArg = createDescriptorForPropertyReferenceArg();
  /*package*/ final ConceptDescriptor myConceptSelect = createDescriptorForSelect();
  /*package*/ final ConceptDescriptor myConceptSelectCard = createDescriptorForSelectCard();
  /*package*/ final ConceptDescriptor myConceptSelectPile = createDescriptorForSelectPile();
  /*package*/ final ConceptDescriptor myConceptSetValue = createDescriptorForSetValue();
  /*package*/ final ConceptDescriptor myConceptShuffle = createDescriptorForShuffle();
  /*package*/ final ConceptDescriptor myConceptStringValue = createDescriptorForStringValue();
  /*package*/ final ConceptDescriptor myConceptToken = createDescriptorForToken();
  /*package*/ final ConceptDescriptor myConceptTopOf = createDescriptorForTopOf();
  /*package*/ final ConceptDescriptor myConceptTurn = createDescriptorForTurn();
  /*package*/ final ConceptDescriptor myConceptValue = createDescriptorForValue();
  /*package*/ final ConceptDescriptor myConceptWhile = createDescriptorForWhile();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptAnd, myConceptArgument, myConceptCard, myConceptCardReference, myConceptCollection, myConceptCommand, myConceptComparator, myConceptDeck, myConceptEmpty, myConceptEquals, myConceptGame, myConceptIfExpression, myConceptInputField, myConceptInputFieldReference, myConceptIntValue, myConceptKamu, myConceptLogicalExpression, myConceptMove, myConceptMoveAll, myConceptMoveSelected, myConceptNot, myConceptOperator, myConceptOptional, myConceptOr, myConceptPhase, myConceptPile, myConceptPileMethod, myConceptPileReference, myConceptPlayer, myConceptProperty, myConceptPropertyReference, myConceptPropertyReferenceArg, myConceptSelect, myConceptSelectCard, myConceptSelectPile, myConceptSetValue, myConceptShuffle, myConceptStringValue, myConceptToken, myConceptTopOf, myConceptTurn, myConceptValue, myConceptWhile);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.And:
        return myConceptAnd;
      case LanguageConceptSwitch.Argument:
        return myConceptArgument;
      case LanguageConceptSwitch.Card:
        return myConceptCard;
      case LanguageConceptSwitch.CardReference:
        return myConceptCardReference;
      case LanguageConceptSwitch.Collection:
        return myConceptCollection;
      case LanguageConceptSwitch.Command:
        return myConceptCommand;
      case LanguageConceptSwitch.Comparator:
        return myConceptComparator;
      case LanguageConceptSwitch.Deck:
        return myConceptDeck;
      case LanguageConceptSwitch.Empty:
        return myConceptEmpty;
      case LanguageConceptSwitch.Equals:
        return myConceptEquals;
      case LanguageConceptSwitch.Game:
        return myConceptGame;
      case LanguageConceptSwitch.IfExpression:
        return myConceptIfExpression;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.IntValue:
        return myConceptIntValue;
      case LanguageConceptSwitch.Kamu:
        return myConceptKamu;
      case LanguageConceptSwitch.LogicalExpression:
        return myConceptLogicalExpression;
      case LanguageConceptSwitch.Move:
        return myConceptMove;
      case LanguageConceptSwitch.MoveAll:
        return myConceptMoveAll;
      case LanguageConceptSwitch.MoveSelected:
        return myConceptMoveSelected;
      case LanguageConceptSwitch.Not:
        return myConceptNot;
      case LanguageConceptSwitch.Operator:
        return myConceptOperator;
      case LanguageConceptSwitch.Optional:
        return myConceptOptional;
      case LanguageConceptSwitch.Or:
        return myConceptOr;
      case LanguageConceptSwitch.Phase:
        return myConceptPhase;
      case LanguageConceptSwitch.Pile:
        return myConceptPile;
      case LanguageConceptSwitch.PileMethod:
        return myConceptPileMethod;
      case LanguageConceptSwitch.PileReference:
        return myConceptPileReference;
      case LanguageConceptSwitch.Player:
        return myConceptPlayer;
      case LanguageConceptSwitch.Property:
        return myConceptProperty;
      case LanguageConceptSwitch.PropertyReference:
        return myConceptPropertyReference;
      case LanguageConceptSwitch.PropertyReferenceArg:
        return myConceptPropertyReferenceArg;
      case LanguageConceptSwitch.Select:
        return myConceptSelect;
      case LanguageConceptSwitch.SelectCard:
        return myConceptSelectCard;
      case LanguageConceptSwitch.SelectPile:
        return myConceptSelectPile;
      case LanguageConceptSwitch.SetValue:
        return myConceptSetValue;
      case LanguageConceptSwitch.Shuffle:
        return myConceptShuffle;
      case LanguageConceptSwitch.StringValue:
        return myConceptStringValue;
      case LanguageConceptSwitch.Token:
        return myConceptToken;
      case LanguageConceptSwitch.TopOf:
        return myConceptTopOf;
      case LanguageConceptSwitch.Turn:
        return myConceptTurn;
      case LanguageConceptSwitch.Value:
        return myConceptValue;
      case LanguageConceptSwitch.While:
        return myConceptWhile;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Action", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.class_(false, true, false);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054552082");
    b.version(3);
    b.alias("action");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAnd() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "And", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b81fc2L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Operator
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b81fbcL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054604738");
    b.version(3);
    b.alias("and");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForArgument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Argument", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.class_(false, true, false);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690311778715");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Card", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b824594L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867653012");
    b.version(3);
    b.aggregate("values", 0x568258613b82e587L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82e0a7L).optional(true).ordered(true).multiple(true).origin("6233642008867693959").done();
    b.alias("card");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCardReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "CardReference", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263e6d407L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Argument
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690311001095");
    b.version(3);
    b.associate("card", 0x25174a6263e6d408L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b824594L).optional(false).origin("2672686690311001096").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCollection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Collection", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x51c0e360de7b4083L);
    b.class_(false, true, false);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/5890958317789593731");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCommand() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Command", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca73L);
    b.class_(false, true, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054582899");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComparator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Comparator", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f04503L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.LogicalExpression
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690311619843");
    b.version(3);
    b.aggregate("left", 0x25174a6263f04504L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL).optional(false).ordered(true).multiple(false).origin("2672686690311619844").done();
    b.aggregate("right", 0x25174a6263f04506L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL).optional(false).ordered(true).multiple(false).origin("2672686690311619846").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDeck() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Deck", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L);
    b.class_(false, false, true);
    // extends: CardGameLanguage.structure.Collection
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x51c0e360de7b4083L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867792839");
    b.version(3);
    b.aggregate("cards", 0x568258613b8467caL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b824594L).optional(true).ordered(true).multiple(true).origin("6233642008867792842").done();
    b.alias("deck");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEmpty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Empty", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca49L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.LogicalExpression
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054582857");
    b.version(3);
    b.associate("pile", 0x26431eee60b8140aL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f83152L).optional(false).origin("2757081406054601738").done();
    b.alias("empty");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEquals() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Equals", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263e0b7f0L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Comparator
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f04503L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690310600688");
    b.version(3);
    b.alias("equals");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGame() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Game", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f86776L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/4158612253542213494");
    b.version(3);
    b.associate("deck", 0x533ca69374a18a98L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(true).origin("5997851955997805208").done();
    b.aggregate("inputfields", 0x94fca76d696ce67L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x94fca76d696ce5cL).optional(true).ordered(true).multiple(true).origin("670977481256652391").done();
    b.aggregate("properties", 0x25174a6263e7f315L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82e0a7L).optional(true).ordered(true).multiple(true).origin("2672686690311074581").done();
    b.aggregate("players", 0x39b65bcfb2f8677dL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f7900fL).optional(true).ordered(true).multiple(true).origin("4158612253542213501").done();
    b.aggregate("phases", 0x26431eee60b1bc59L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b1bc56L).optional(false).ordered(true).multiple(true).origin("2757081406054186073").done();
    b.alias("game");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIfExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "IfExpression", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263dd595bL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Command
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca73L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690310379867");
    b.version(3);
    b.aggregate("condition", 0x25174a6263dd595cL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL).optional(false).ordered(true).multiple(false).origin("2672686690310379868").done();
    b.aggregate("true", 0x25174a6263dd595eL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(true).ordered(true).multiple(true).origin("2672686690310379870").done();
    b.aggregate("false", 0x25174a6263dd5961L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(true).ordered(true).multiple(true).origin("2672686690310379873").done();
    b.alias("if");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "InputField", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x94fca76d696ce5cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/670977481256652380");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "InputFieldReference", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x94fca76d696ce6cL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Argument
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/670977481256652396");
    b.version(3);
    b.associate("inputfield", 0x94fca76d696ce6dL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x94fca76d696ce5cL).optional(false).origin("670977481256652397").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "IntValue", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82ce75L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Value
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82ce7bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867688053");
    b.version(3);
    b.property("value", 0x568258613b82ce77L).type(PrimitiveTypeId.INTEGER).origin("6233642008867688055").done();
    b.alias("Number");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKamu() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Kamu", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b85597L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054618519");
    b.version(3);
    b.alias("kamu");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLogicalExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "LogicalExpression", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL);
    b.class_(false, true, false);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054582846");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMove() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Move", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75215L);
    b.class_(false, false, true);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054552085");
    b.version(3);
    b.property("number", 0x26431eee60b77132L).type(PrimitiveTypeId.INTEGER).origin("2757081406054560050").done();
    b.associate("from", 0x26431eee60b75216L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(false).origin("2757081406054552086").done();
    b.associate("to", 0x26431eee60b75218L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(false).origin("2757081406054552088").done();
    b.alias("move");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoveAll() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "MoveAll", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b79ac9L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054570697");
    b.version(3);
    b.associate("from", 0x26431eee60b7a376L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(false).origin("2757081406054572918").done();
    b.associate("to", 0x26431eee60b7a378L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(false).origin("2757081406054572920").done();
    b.alias("move all");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoveSelected() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "MoveSelected", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7b86cL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054578284");
    b.version(3);
    b.associate("from", 0x708948e1d0f7bd4L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f83152L).optional(false).origin("506818296173001684").done();
    b.associate("to", 0x708948e1d0f7c60L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f83152L).optional(false).origin("506818296173001824").done();
    b.aggregate("select", 0x708948e1d0cea8aL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b88f78L).optional(false).ordered(true).multiple(false).origin("506818296172833418").done();
    b.alias("move selected");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNot() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Not", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3dL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.LogicalExpression
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054582845");
    b.version(3);
    b.aggregate("expression", 0x26431eee60b7ca47L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL).optional(false).ordered(true).multiple(false).origin("2757081406054582855").done();
    b.alias("not");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOperator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Operator", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b81fbcL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.LogicalExpression
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054604732");
    b.version(3);
    b.aggregate("left", 0x26431eee60b81fbdL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL).optional(false).ordered(true).multiple(false).origin("2757081406054604733").done();
    b.aggregate("right", 0x26431eee60b81fbfL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL).optional(false).ordered(true).multiple(false).origin("2757081406054604735").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOptional() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Optional", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b85598L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054618520");
    b.version(3);
    b.aggregate("action", 0x26431eee60b85599L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(false).ordered(true).multiple(false).origin("2757081406054618521").done();
    b.aggregate("iftrue", 0x51c0e360de84c498L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(true).ordered(true).multiple(true).origin("5890958317790217368").done();
    b.alias("optional");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOr() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Or", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b81fc3L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Operator
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b81fbcL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054604739");
    b.version(3);
    b.alias("or");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPhase() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Phase", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b1bc56L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054186070");
    b.version(3);
    b.aggregate("actions", 0x26431eee60b75213L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(true).ordered(true).multiple(true).origin("2757081406054552083").done();
    b.alias("phase");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Pile", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f83152L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Deck
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/4158612253542199634");
    b.version(3);
    b.alias("pile");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPileMethod() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "PileMethod", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f7de45L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Argument
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690312117829");
    b.version(3);
    b.aggregate("pilereference", 0x25174a6263f7de48L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f7de4bL).optional(false).ordered(true).multiple(false).origin("2672686690312117832").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPileReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "PileReference", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f7de4bL);
    b.class_(false, false, false);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690312117835");
    b.version(3);
    b.associate("pile", 0x25174a6263f7de4cL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f83152L).optional(false).origin("2672686690312117836").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlayer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Player", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f7900fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/4158612253542158351");
    b.version(3);
    b.associate("deck", 0x26431eee60b781d6L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(true).origin("2757081406054564310").done();
    b.aggregate("collections", 0x51c0e360de7b4089L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x51c0e360de7b4083L).optional(true).ordered(true).multiple(true).origin("5890958317789593737").done();
    b.alias("player");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProperty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Property", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82e0a7L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Argument
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867692711");
    b.version(3);
    b.aggregate("propertyValue", 0x568258613b82e0aaL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82ce7bL).optional(false).ordered(true).multiple(false).origin("6233642008867692714").done();
    b.alias("property");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertyReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "PropertyReference", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263ec6f50L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690311368528");
    b.version(3);
    b.associate("property", 0x25174a6263ec6f51L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82e0a7L).optional(false).origin("2672686690311368529").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertyReferenceArg() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "PropertyReferenceArg", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f42e25L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Argument
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690311876133");
    b.version(3);
    b.associate("property", 0x25174a6263f42e26L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82e0a7L).optional(false).origin("2672686690311876134").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSelect() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Select", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b88f78L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054633336");
    b.version(3);
    b.alias("select card");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSelectCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "SelectCard", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b88f7cL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Select
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b88f78L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054633340");
    b.version(3);
    b.alias("select card");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSelectPile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "SelectPile", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b88f79L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Select
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b88f78L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054633337");
    b.version(3);
    b.associate("pile", 0x26431eee60b88f7aL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x39b65bcfb2f83152L).optional(false).origin("2757081406054633338").done();
    b.alias("select pile");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSetValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "SetValue", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263eb49dbL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690311293403");
    b.version(3);
    b.aggregate("left", 0x25174a6263eef3eeL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263ec6f50L).optional(false).ordered(true).multiple(false).origin("2672686690311533550").done();
    b.aggregate("right", 0x25174a6263eef3f0L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("2672686690311533552").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShuffle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Shuffle", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b76900L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054557952");
    b.version(3);
    b.associate("deck", 0x26431eee60b76901L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b8467c7L).optional(false).origin("2757081406054557953").done();
    b.alias("shuffle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStringValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "StringValue", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82ce76L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Value
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82ce7bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867688054");
    b.version(3);
    b.property("value", 0x568258613b82ce79L).type(PrimitiveTypeId.STRING).origin("6233642008867688057").done();
    b.alias("Text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToken() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Token", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b824595L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Collection
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x51c0e360de7b4083L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867653013");
    b.version(3);
    b.aggregate("value", 0x39b65bcfb2f78fedL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82e0a7L).optional(false).ordered(true).multiple(false).origin("4158612253542158317").done();
    b.alias("token");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTopOf() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "TopOf", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f7de44L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.PileMethod
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f7de45L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2672686690312117828");
    b.version(3);
    b.alias("top of");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTurn() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Turn", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b82ce6L);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Action
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054608102");
    b.version(3);
    b.aggregate("actions", 0x26431eee60b82ce7L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(true).ordered(true).multiple(true).origin("2757081406054608103").done();
    b.alias("turn");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "Value", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x568258613b82ce7bL);
    b.class_(false, true, false);
    // extends: CardGameLanguage.structure.Argument
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x25174a6263f2b19bL);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/6233642008867688059");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWhile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CardGameLanguage", "While", 0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca4aL);
    b.class_(false, false, false);
    // extends: CardGameLanguage.structure.Command
    b.super_(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca73L);
    b.origin("r:afcff3ea-f21b-45f4-91f1-e25c88e4b8f5(CardGameLanguage.structure)/2757081406054582858");
    b.version(3);
    b.aggregate("condition", 0x26431eee60b7ca66L).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b7ca3eL).optional(false).ordered(true).multiple(false).origin("2757081406054582886").done();
    b.aggregate("body", 0x26431eee60b7ca6cL).target(0xe94dfae4e9d04770L, 0x965c58db5e543504L, 0x26431eee60b75212L).optional(true).ordered(true).multiple(true).origin("2757081406054582892").done();
    b.alias("while");
    return b.create();
  }
}
