package Runtime.JavaCode;

/*Generated by MPS */

import java.util.ArrayList;

public class Card {
  /*package*/ String name;
  /*package*/ ArrayList<Property> properties = new ArrayList<>();

  public Card(String name) {
    this.name = name;
  }

  public Card() {
  }

  public void addProperty(Property property) {
    properties.add(property);
  }
}
