package Runtime.JavaCode;

/*Generated by MPS */

import java.util.ArrayList;

public class DeckRuntime extends Collection {
  private ArrayList<Card> cards = new ArrayList<Card>();


  public void addCard(Card card) {
    cards.add(card);
  }

  public void print() {
    System.out.println("DeckRuntimePrint");
  }
}
