package Runtime.JavaCode;

/*Generated by MPS */

import java.util.ArrayList;

public class GameRuntime {
  /*package*/ ArrayList<PlayerRuntime> players = new ArrayList<>();
  /*package*/ ArrayList<Phase> phases = new ArrayList<>();

  public void addPlayer(PlayerRuntime playerRuntime) {
    players.add(playerRuntime);
  }
  public void addPhase(Phase phase) {
    phases.add(phase);
  }
  public void StartGame() {
  }
}
