package Runtime.JavaCode;

/*Generated by MPS */


public class IntProperty extends Property {
  /*package*/ String propertyName;
  /*package*/ int propertyValue;

  public IntProperty(String name, int value) {
    propertyName = name;
    propertyValue = value;
  }
}
