package Runtime.JavaCode;

/*Generated by MPS */

import java.util.ArrayList;

public class PlayerRuntime {
  /*package*/ ArrayList<Collection> playerCollections = new ArrayList<Collection>();

  public void addCollection(Collection collection) {
    playerCollections.add(collection);
  }

}
