package Runtime.JavaCode;

/*Generated by MPS */


public class stringProperty extends Property {
  /*package*/ String propertyName;
  /*package*/ String propertyValue;

  public stringProperty(String name, String value) {
    propertyName = name;
    propertyValue = value;
  }
}
