package Runtime.JavaCode;

/*Generated by MPS */


public class stringProperty {

  /*package*/ String propertyValue;

  public stringProperty(String name, String value) {
    propertyValue = value;
  }
}
