package CardGameLanguage.sandbox;

/*Generated by MPS */

import Runtime.JavaCode.GameRuntime;
import Runtime.JavaCode.PlayerRuntime;

public class CarComparisonGame extends GameRuntime {
  public static GameRuntime game = new GameRuntime();

  public static void main(String[] args) {
    {
      PlayerRuntime Alice = new PlayerRuntime();
      game.addPlayer(Alice);
    }
    {
      PlayerRuntime Bob = new PlayerRuntime();
      game.addPlayer(Bob);
    }
    {
      PlayerRuntime Cecil = new PlayerRuntime();
      game.addPlayer(Cecil);
    }
    {
      PlayerRuntime Board = new PlayerRuntime();
      game.addPlayer(Board);
    }
    game.StartGame();
  }

  public void Setup() {
  }
  public void MainPhase() {
  }

}
