package CardGameLanguage.sandbox;

/*Generated by MPS */

import Runtime.JavaCode.Card;
import Runtime.JavaCode.DeckRuntime;
import Runtime.JavaCode.Property;

public class Cars extends Card {
  public static DeckRuntime deckRuntime = new DeckRuntime();
  public void init() {
    {
      Card Porsche911 = new Card("Porsche911");
      deckRuntime.addCard(Porsche911);
      Porsche911.addProperty(new Property("Top Speed", 320));
      Porsche911.addProperty(new Property("Horsepower", 473));
      Porsche911.addProperty(new Property("Weight", 1510));
      Porsche911.addProperty(new Property("Popularity", 5));

    }
    {
      Card LamborghiniHuracan = new Card("LamborghiniHuracan");
      deckRuntime.addCard(LamborghiniHuracan);
      LamborghiniHuracan.addProperty(new Property("Top Speed", 323));
      LamborghiniHuracan.addProperty(new Property("Horsepower", 630));
      LamborghiniHuracan.addProperty(new Property("Weight", 1382));
      LamborghiniHuracan.addProperty(new Property("Popularity", 7));

    }
    {
      Card FerrariF150 = new Card("FerrariF150");
      deckRuntime.addCard(FerrariF150);
      FerrariF150.addProperty(new Property("Top Speed", 352));
      FerrariF150.addProperty(new Property("Horsepower", 800));
      FerrariF150.addProperty(new Property("Weight", 1646));
      FerrariF150.addProperty(new Property("Popularity", 8));

    }
    {
      Card NissanSkyline = new Card("NissanSkyline");
      deckRuntime.addCard(NissanSkyline);
      NissanSkyline.addProperty(new Property("Top Speed", 398));
      NissanSkyline.addProperty(new Property("Horsepower", 276));
      NissanSkyline.addProperty(new Property("Weight", 1560));
      NissanSkyline.addProperty(new Property("Popularity", 10));

    }
    {
      Card MazdaRX7 = new Card("MazdaRX7");
      deckRuntime.addCard(MazdaRX7);
      MazdaRX7.addProperty(new Property("Top Speed", 198));
      MazdaRX7.addProperty(new Property("Horsepower", 237));
      MazdaRX7.addProperty(new Property("Weight", 1600));
      MazdaRX7.addProperty(new Property("Popularity", 9));

    }
    {
      Card ToyotaSupra = new Card("ToyotaSupra");
      deckRuntime.addCard(ToyotaSupra);
      ToyotaSupra.addProperty(new Property("Top Speed", 326));
      ToyotaSupra.addProperty(new Property("Horsepower", 262));
      ToyotaSupra.addProperty(new Property("Weight", 1702));
      ToyotaSupra.addProperty(new Property("Popularity", 8));

    }
    {
      Card DodgeViper = new Card("DodgeViper");
      deckRuntime.addCard(DodgeViper);
      DodgeViper.addProperty(new Property("Top Speed", 332));
      DodgeViper.addProperty(new Property("Horsepower", 460));
      DodgeViper.addProperty(new Property("Weight", 1963));
      DodgeViper.addProperty(new Property("Popularity", 5));

    }
    {
      Card FordGTR = new Card("FordGTR");
      deckRuntime.addCard(FordGTR);
      FordGTR.addProperty(new Property("Top Speed", 329));
      FordGTR.addProperty(new Property("Horsepower", 467));
      FordGTR.addProperty(new Property("Weight", 1879));
      FordGTR.addProperty(new Property("Popularity", 5));

    }
    {
      Card ChevroletCorvette = new Card("ChevroletCorvette");
      deckRuntime.addCard(ChevroletCorvette);
      ChevroletCorvette.addProperty(new Property("Top Speed", 363));
      ChevroletCorvette.addProperty(new Property("Horsepower", 442));
      ChevroletCorvette.addProperty(new Property("Weight", 1635));
      ChevroletCorvette.addProperty(new Property("Popularity", 8));

    }
    {
      Card AstonMartinDB9 = new Card("AstonMartinDB9");
      deckRuntime.addCard(AstonMartinDB9);
      AstonMartinDB9.addProperty(new Property("Top Speed", 299));
      AstonMartinDB9.addProperty(new Property("Horsepower", 315));
      AstonMartinDB9.addProperty(new Property("Weight", 2256));
      AstonMartinDB9.addProperty(new Property("Popularity", 7));

    }
    {
      Card LotusElise = new Card("LotusElise");
      deckRuntime.addCard(LotusElise);
      LotusElise.addProperty(new Property("Top Speed", 267));
      LotusElise.addProperty(new Property("Horsepower", 253));
      LotusElise.addProperty(new Property("Weight", 1115));
      LotusElise.addProperty(new Property("Popularity", 5));

    }
    {
      Card BugattiVeyron = new Card("BugattiVeyron");
      deckRuntime.addCard(BugattiVeyron);
      BugattiVeyron.addProperty(new Property("Top Speed", 378));
      BugattiVeyron.addProperty(new Property("Horsepower", 673));
      BugattiVeyron.addProperty(new Property("Weight", 1785));
      BugattiVeyron.addProperty(new Property("Popularity", 7));

    }
  }

}
