package CardGameLanguage.sandbox;

/*Generated by MPS */

import Runtime.JavaCode.GameRuntime;
import Runtime.JavaCode.PlayerRuntime;

public class Kamu extends GameRuntime {
  public static GameRuntime game = new GameRuntime();

  public static void main(String[] args) {
    {
      PlayerRuntime Player = new PlayerRuntime();
      game.addPlayer(Player);
    }
    {
      PlayerRuntime Board = new PlayerRuntime();
      game.addPlayer(Board);
    }
    {
      PlayerRuntime Computer = new PlayerRuntime();
      game.addPlayer(Computer);
    }
    game.StartGame();
  }

  public void Setup() {
  }
  public void Main() {
  }

}
