package runtime;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class Card {

  private List<Property> properties = new ArrayList<>();
  private String name;

  public Card(String cardname) {
    name = cardname;
  }

  public String getName() {
    return name;
  }
  public void addProperty(Property p) {
    properties.add(p);
  }
}
