package runtime;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class Deck {


  private List<Card> cards = new ArrayList<>();

  public void addCard(Card card) {
    cards.add(card);
  }

  public void removeCard(Card card) {
    cards.remove(card);
  }

  public void listAllCards() {
    for (int i = 0; i < cards.size(); i++) {
      System.out.println(cards.get(i).getName());
    }
  }
}
